### PR TITLE
try to fix #3. Works for commonJS now, EJS not tested and try 

### LINKED ISSUE #1: reuse of existing ws connection
hi
would it be possible to use an existing ws connection?
the ws server could be the rest client... and it would adapt to my use case :)

### LINKED ISSUE #3: tinyws for commonJS
is there a way to use tinyws in commonJS. I got some legacy code.

### PR DESCRIPTION
**Pull request by franckOL**
Signed-off-by: ROUDET Franck INNOV/IT-S <franck.roudet@orange.com>

### CODE REVIEW

**Comment by talentlessguy** [comment]
ummm no I won't add CJS support to tinyws. it's a step back to past.

see this: https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77?gi=1cf23e9f6390

**Comment by franckOL** [comment]
I think I loose index.d.js

**Comment by franckOL** [comment]
I understand @talentlessguy , but it helps to start adoption to tinyWS, and seems not to hard to do.

**Comment by franckOL** [comment]
You don't want to have a look ?

**Comment by talentlessguy** [comment]
@franckOL meh, this lib is intended to be used in ESM environments, I don't see a reason to add CJS fallback

it's the same reason I wouldn't want to support IE11 if I was developing a website

**Pull request closed without merging**
